import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { test } from "node:test";
import { createClient } from "@supabase/supabase-js";
const require=createRequire(import.meta.url);const bin=require.resolve("supabase/dist/supabase.js");const {API_URL:url,PUBLISHABLE_KEY:key,SERVICE_ROLE_KEY:secret}=JSON.parse(execFileSync(process.execPath,[bin,"status","--output","json"],{encoding:"utf8"}));const trusted=createClient(url,secret,{auth:{persistSession:false}});
async function admin(){const email=`cms-${crypto.randomUUID()}@example.invalid`,password=`Cms-${crypto.randomUUID()}!`;const{data,error}=await trusted.auth.admin.createUser({email,password,email_confirm:true});assert.ifError(error);assert.ifError((await trusted.from("admin_profiles").insert({user_id:data.user.id})).error);const client=createClient(url,key,{auth:{persistSession:false}});assert.ifError((await client.auth.signInWithPassword({email,password})).error);return{client,id:data.user.id};}
async function remove(id){await trusted.from("admin_profiles").delete().eq("user_id",id);await trusted.auth.admin.deleteUser(id);}
test("Admin prompt RPC creates and edits the complete Prompt atomically",async()=>{const{client,id}=await admin();let promptId;try{const payload={title:"RPC Prompt",slug:`rpc-${crypto.randomUUID()}`,short_description:"RPC draft",description:null,prompt_template:"Render {subject}",generation_notes:null,access_type:"FREE",category_id:"00000000-0000-4000-8000-000000000101",aspect_ratio:"1:1",orientation:"SQUARE",requires_reference_image:false,primary_sales_pack_id:null,status:"DRAFT",asset_id:null,image_alt:null,model_ids:["00000000-0000-4000-8000-000000000201"],tag_ids:[],use_case_ids:[],variables:[{key:"subject",label:"Subject",required:true,sort_order:0}]};const created=await client.rpc("save_admin_prompt",{p_prompt_id:null,p_data:payload});assert.ifError(created.error);promptId=created.data;const edited=await client.rpc("save_admin_prompt",{p_prompt_id:promptId,p_data:{...payload,title:"RPC Prompt Edited",prompt_template:"Draw {subject}"}});assert.ifError(edited.error);const{data,rowError}=await trusted.from("prompts").select("title,prompt_contents(prompt_template),prompt_variables(key)").eq("id",promptId).single();assert.ifError(rowError);assert.equal(data.title,"RPC Prompt Edited");assert.equal(data.prompt_contents.prompt_template,"Draw {subject}");assert.equal(data.prompt_variables[0].key,"subject");}finally{if(promptId)await trusted.from("prompts").delete().eq("id",promptId);await remove(id);}});

test("Admin pack RPC publishes eligible Premium drafts in the same transaction",async()=>{const{client,id}=await admin();let packId,assetId;const promptId="00000000-0000-4000-8000-000000000602";try{const asset=await trusted.from("media_assets").insert({bucket:"prompt-previews",storage_path:`cms-test/${crypto.randomUUID()}.webp`,mime_type:"image/webp",byte_size:1,width:1,height:1,created_by:id}).select("id").single();assert.ifError(asset.error);assetId=asset.data.id;assert.ifError((await trusted.from("prompts").update({access_type:"PACK_ONLY"}).eq("id",promptId)).error);const result=await client.rpc("save_admin_pack",{p_pack_id:null,p_data:{title:"Atomic pack",slug:`atomic-${crypto.randomUUID()}`,description:"Atomic publication",cover_asset_id:assetId,price_minor:59000,currency:"IDR",status:"PUBLISHED",prompt_ids:[promptId]}});assert.ifError(result.error);packId=result.data;const{data:prompt,error}=await trusted.from("prompts").select("status,primary_sales_pack_id").eq("id",promptId).single();assert.ifError(error);assert.deepEqual(prompt,{status:"PUBLISHED",primary_sales_pack_id:packId});
}finally{if(packId){execFileSync("docker",["exec","-i","supabase_db_renderbank","psql","-X","-v","ON_ERROR_STOP=1","-U","postgres","-d","postgres"],{input:`begin; update public.packs set status='ARCHIVED' where id='${packId}'; update public.prompts set access_type='FREE',status='DRAFT',primary_sales_pack_id=null,published_at=null where id='${promptId}'; delete from public.packs where id='${packId}'; commit;`,encoding:"utf8"});}if(assetId)assert.ifError((await trusted.from("media_assets").delete().eq("id",assetId)).error);await remove(id);}});
